#!/bin/bash
IN=kursgraf.dot
ENGINES=(dot neato sfdp fdp)

if [[ "$1" = "reduce" ]]; then
	FP=`mktemp`
	tred $IN > $FP
	IN=$FP
fi

for eng in ${ENGINES[@]}; do
	command $eng $IN -Tpdf > "kursgraf_$eng.pdf"
done

rm $FP
